In [1]:
import pandas as pd
df = pd.read_csv("datas/Chicago_Crimes_2001_to_Present.csv")

/tmp/ipykernel_179718/2811462094.py:2: DtypeWarning: Columns (0: IUCR) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("datas/Chicago_Crimes_2001_to_Present.csv")

In [2]:
import numpy as np
import matplotlib.pylab as plt
import seaborn as sns
plt.style.use('ggplot')

### Exploring Data

In [2]:
df

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,13311263,JG503434,07/29/2022 03:39:00 AM,023XX S TROY ST,1582,OFFENSE INVOLVING CHILDREN,CHILD PORNOGRAPHY,RESIDENCE,True,False,...,25.0,30.0,17,NaN,NaN,2022,04/18/2024 03:40:59 PM,NaN,NaN,NaN
1,13053066,JG103252,01/03/2023 04:44:00 PM,039XX W WASHINGTON BLVD,2017,NARCOTICS,MANUFACTURE / DELIVER - CRACK,SIDEWALK,True,False,...,28.0,26.0,18,NaN,NaN,2023,01/20/2024 03:41:12 PM,NaN,NaN,NaN
2,12131221,JD327000,08/10/2020 09:45:00 AM,015XX N DAMEN AVE,0326,ROBBERY,AGGRAVATED VEHICULAR HIJACKING,STREET,True,False,...,1.0,24.0,03,1162795.0,1909900.0,2020,05/17/2025 03:40:52 PM,41.908418,-87.677407,"(41.908417822, -87.67740693)"
3,11227634,JB147599,08/26/2017 10:00:00 AM,001XX W RANDOLPH ST,0281,CRIM SEXUAL ASSAULT,NON-AGGRAVATED,HOTEL/MOTEL,False,False,...,42.0,32.0,02,NaN,NaN,2017,02/11/2018 03:57:41 PM,NaN,NaN,NaN
4,13203321,JG415333,09/06/2023 05:00:00 PM,002XX N Wells st,1320,CRIMINAL DAMAGE,TO VEHICLE,PARKING LOT / GARAGE (NON RESIDENTIAL),False,False,...,42.0,32.0,14,1174694.0,1901831.0,2023,11/04/2023 03:40:18 PM,41.886018,-87.633938,"(41.886018055, -87.633937881)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8422091,13991734,JJ444423,10/07/2025 09:00:00 PM,010XX N MILWAUKEE AVE,0910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,...,27.0,24.0,07,1166630.0,1907361.0,2025,10/15/2025 03:55:37 PM,41.901369,-87.663392,"(41.901369302, -87.663391932)"
8422092,13991229,JJ443785,10/07/2025 10:26:00 PM,079XX S HALSTED ST,0454,BATTERY,"AGGRAVATED P.O. - HANDS, FISTS, FEET, NO / MIN...",PARKING LOT / GARAGE (NON RESIDENTIAL),True,False,...,17.0,71.0,08B,1172344.0,1852279.0,2025,10/15/2025 03:55:37 PM,41.750095,-87.644027,"(41.750094836, -87.644027249)"
8422093,13996340,JJ449975,09/29/2025 05:20:00 PM,027XX W MONTROSE AVE,0760,BURGLARY,BURGLARY FROM MOTOR VEHICLE,STREET,False,False,...,33.0,16.0,06,1157140.0,1929112.0,2025,10/15/2025 03:51:58 PM,41.961254,-87.697657,"(41.961253689, -87.697657333)"
8422094,13990920,JJ443318,10/07/2025 02:56:00 PM,089XX S WALLACE ST,0486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,False,True,...,21.0,71.0,08B,1173869.0,1845664.0,2025,10/15/2025 03:55:37 PM,41.731909,-87.638635,"(41.731908752, -87.638634675)"
8422095,13990549,JJ442752,10/07/2025 03:30:00 AM,131XX S CARONDOLET AVE,1320,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,False,...,10.0,55.0,14,1198434.0,1818345.0,2025,10/15/2025 03:55:37 PM,41.656363,-87.549555,"(41.65636344, -87.549555301)"

In [3]:
df.dtypes

ID                        int64
Case Number                 str
Date                        str
Block                       str
IUCR                     object
Primary Type                str
Description                 str
Location Description        str
Arrest                     bool
Domestic                   bool
Beat                      int64
District                float64
Ward                    float64
Community Area          float64
FBI Code                    str
X Coordinate            float64
Y Coordinate            float64
Year                      int64
Updated On                  str
Latitude                float64
Longitude               float64
Location                    str
dtype: object

In [5]:
df["Beat"]

0          1033
1          1122
2          1424
3           122
4           122
           ...
8422091    1213
8422092     621
8422093    1724
8422094    2223
8422095     433
Name: Beat, Length: 8422096, dtype: int64

In [8]:
df["District"]

0          10.0
1          11.0
2          14.0
3           1.0
4           1.0
           ...
8422091    12.0
8422092     6.0
8422093    17.0
8422094    22.0
8422095     4.0
Name: District, Length: 8422096, dtype: float64

In [9]:
df["Date"]

0          07/29/2022 03:39:00 AM
1          01/03/2023 04:44:00 PM
2          08/10/2020 09:45:00 AM
3          08/26/2017 10:00:00 AM
4          09/06/2023 05:00:00 PM
                    ...
8422091    10/07/2025 09:00:00 PM
8422092    10/07/2025 10:26:00 PM
8422093    09/29/2025 05:20:00 PM
8422094    10/07/2025 02:56:00 PM
8422095    10/07/2025 03:30:00 AM
Name: Date, Length: 8422096, dtype: str

In [3]:
df["Date"] = pd.to_datetime(df["Date"])  # Tarihler string olarak değil, datetime olarak incelenmeli

In [25]:
df.dtypes

ID                               int64
Case Number                        str
Date                    datetime64[us]
Block                              str
IUCR                            object
Primary Type                       str
Description                        str
Location Description               str
Arrest                            bool
Domestic                          bool
Beat                             int64
District                       float64
Ward                           float64
Community Area                 float64
FBI Code                           str
X Coordinate                   float64
Y Coordinate                   float64
Updated On                         str
Latitude                       float64
Longitude                      float64
Location                           str
dtype: object

In [26]:
df["Date"].min()

Timestamp('2001-01-01 00:00:00')

In [14]:
df["Primary Type"].value_counts().size

34

34 farklı suç tip var.

In [15]:
df["Location Description"].value_counts()

Location Description
STREET                    2200652
RESIDENCE                 1383097
APARTMENT                 1000712
SIDEWALK                   762500
OTHER                      269937
                           ...
POLICE FACILITY                 1
JUNK YARD/GARBAGE DUMP          1
FUNERAL PARLOR                  1
LIVERY AUTO                     1
LOADING DOCK                    1
Name: count, Length: 218, dtype: int64

In [4]:
df.drop(columns=["Year"], inplace=True)   # zaten elimde datetime türünde tarih olduğu için buna gerek yok.

- NaN values kontrolü

In [29]:
df.isna().sum()

ID                           0
Case Number                  0
Date                         0
Block                        0
IUCR                         0
Primary Type                 0
Description                  0
Location Description     14978
Arrest                       0
Domestic                     0
Beat                         0
District                    47
Ward                    614822
Community Area          613687
FBI Code                     0
X Coordinate             93844
Y Coordinate             93844
Updated On                   0
Latitude                 93844
Longitude                93844
Location                 93844
dtype: int64

In [30]:
df[df["Location Description"].isna()]

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Updated On,Latitude,Longitude,Location
86,13340773,JH118602,2023-12-11 14:15:00,011XX N MONITOR AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,NaN,False,False,...,15.0,29.0,25.0,11,1137147.0,1907077.0,01/19/2024 03:40:50 PM,41.901171,-87.771694,"(41.901170711, -87.771693958)"
418,13207457,JG419448,2023-09-06 14:20:00,032XX N OCONTO AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,NaN,False,False,...,16.0,29.0,17.0,11,1127183.0,1920736.0,09/14/2023 03:43:09 PM,41.938826,-87.807986,"(41.938825971, -87.807986017)"
849,13340772,JH118599,2023-11-01 14:05:00,011XX W Madison St,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,NaN,False,False,...,12.0,34.0,28.0,11,1168675.0,1900186.0,01/19/2024 03:40:50 PM,41.881637,-87.656088,"(41.881636544, -87.656088495)"
939,13209655,JG422078,2023-05-30 09:30:00,003XX W WASHINGTON ST,1242,DECEPTIVE PRACTICE,COMPUTER FRAUD,NaN,False,False,...,1.0,42.0,32.0,11,1174189.0,1900801.0,09/16/2023 03:41:56 PM,41.883203,-87.635823,"(41.883202953, -87.635823077)"
1192,13203348,JG415071,2023-09-07 14:35:00,052XX S NATCHEZ AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,NaN,False,False,...,8.0,23.0,56.0,11,1133934.0,1869033.0,09/15/2023 03:42:23 PM,41.796829,-87.784389,"(41.79682922, -87.784389067)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8421536,13997816,JJ451215,2021-06-14 04:18:00,021XX S INDIANA AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,NaN,False,False,...,1.0,3.0,33.0,11,NaN,NaN,10/15/2025 03:55:37 PM,NaN,NaN,NaN
8421734,13996789,JJ450326,2025-04-21 16:20:00,061XX S Sacramento Ave,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,NaN,False,False,...,8.0,15.0,66.0,11,1157438.0,1863692.0,10/15/2025 03:51:58 PM,41.781729,-87.698341,"(41.781728556, -87.698340988)"
8421787,13996755,JJ450389,2025-09-17 17:20:00,054XX W HADDON AVE,1154,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT $300 AND UNDER,NaN,False,False,...,15.0,37.0,25.0,11,1139676.0,1907128.0,10/15/2025 03:51:58 PM,41.901265,-87.762403,"(41.901264852, -87.76240333)"
8421814,13997808,JJ450790,2025-10-06 11:30:00,008XX W MONROE ST,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,NaN,False,False,...,12.0,34.0,28.0,11,NaN,NaN,10/15/2025 03:55:37 PM,NaN,NaN,NaN
8421891,13996762,JJ450018,2025-04-10 00:00:00,026XX N PULASKI RD,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,NaN,False,False,...,25.0,31.0,22.0,11,1149270.0,1917283.0,10/15/2025 03:51:58 PM,41.928951,-87.726900,"(41.928950523, -87.726899566)"

15k ya yakın suç kaydında suçun gerçekleştiği yerin türü (Location Descriptive) NaN bırakılmış. Bu sütunlardaki diğer bilgiler değerini koruduğundan bu kısmı şimdilik "UNKNOWN" yapacağım.

In [5]:
df["Location Description"] = df["Location Description"].fillna("UNKNOWN")
df

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Updated On,Latitude,Longitude,Location
0,13311263,JG503434,2022-07-29 03:39:00,023XX S TROY ST,1582,OFFENSE INVOLVING CHILDREN,CHILD PORNOGRAPHY,RESIDENCE,True,False,...,10.0,25.0,30.0,17,NaN,NaN,04/18/2024 03:40:59 PM,NaN,NaN,NaN
1,13053066,JG103252,2023-01-03 16:44:00,039XX W WASHINGTON BLVD,2017,NARCOTICS,MANUFACTURE / DELIVER - CRACK,SIDEWALK,True,False,...,11.0,28.0,26.0,18,NaN,NaN,01/20/2024 03:41:12 PM,NaN,NaN,NaN
2,12131221,JD327000,2020-08-10 09:45:00,015XX N DAMEN AVE,0326,ROBBERY,AGGRAVATED VEHICULAR HIJACKING,STREET,True,False,...,14.0,1.0,24.0,03,1162795.0,1909900.0,05/17/2025 03:40:52 PM,41.908418,-87.677407,"(41.908417822, -87.67740693)"
3,11227634,JB147599,2017-08-26 10:00:00,001XX W RANDOLPH ST,0281,CRIM SEXUAL ASSAULT,NON-AGGRAVATED,HOTEL/MOTEL,False,False,...,1.0,42.0,32.0,02,NaN,NaN,02/11/2018 03:57:41 PM,NaN,NaN,NaN
4,13203321,JG415333,2023-09-06 17:00:00,002XX N Wells st,1320,CRIMINAL DAMAGE,TO VEHICLE,PARKING LOT / GARAGE (NON RESIDENTIAL),False,False,...,1.0,42.0,32.0,14,1174694.0,1901831.0,11/04/2023 03:40:18 PM,41.886018,-87.633938,"(41.886018055, -87.633937881)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8422091,13991734,JJ444423,2025-10-07 21:00:00,010XX N MILWAUKEE AVE,0910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,...,12.0,27.0,24.0,07,1166630.0,1907361.0,10/15/2025 03:55:37 PM,41.901369,-87.663392,"(41.901369302, -87.663391932)"
8422092,13991229,JJ443785,2025-10-07 22:26:00,079XX S HALSTED ST,0454,BATTERY,"AGGRAVATED P.O. - HANDS, FISTS, FEET, NO / MIN...",PARKING LOT / GARAGE (NON RESIDENTIAL),True,False,...,6.0,17.0,71.0,08B,1172344.0,1852279.0,10/15/2025 03:55:37 PM,41.750095,-87.644027,"(41.750094836, -87.644027249)"
8422093,13996340,JJ449975,2025-09-29 17:20:00,027XX W MONTROSE AVE,0760,BURGLARY,BURGLARY FROM MOTOR VEHICLE,STREET,False,False,...,17.0,33.0,16.0,06,1157140.0,1929112.0,10/15/2025 03:51:58 PM,41.961254,-87.697657,"(41.961253689, -87.697657333)"
8422094,13990920,JJ443318,2025-10-07 14:56:00,089XX S WALLACE ST,0486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,False,True,...,22.0,21.0,71.0,08B,1173869.0,1845664.0,10/15/2025 03:55:37 PM,41.731909,-87.638635,"(41.731908752, -87.638634675)"
8422095,13990549,JJ442752,2025-10-07 03:30:00,131XX S CARONDOLET AVE,1320,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,False,...,4.0,10.0,55.0,14,1198434.0,1818345.0,10/15/2025 03:55:37 PM,41.656363,-87.549555,"(41.65636344, -87.549555301)"

In [32]:
df[df["Location Description"] == "UNKNOWN"]

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Updated On,Latitude,Longitude,Location
86,13340773,JH118602,2023-12-11 14:15:00,011XX N MONITOR AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,UNKNOWN,False,False,...,15.0,29.0,25.0,11,1137147.0,1907077.0,01/19/2024 03:40:50 PM,41.901171,-87.771694,"(41.901170711, -87.771693958)"
418,13207457,JG419448,2023-09-06 14:20:00,032XX N OCONTO AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,UNKNOWN,False,False,...,16.0,29.0,17.0,11,1127183.0,1920736.0,09/14/2023 03:43:09 PM,41.938826,-87.807986,"(41.938825971, -87.807986017)"
849,13340772,JH118599,2023-11-01 14:05:00,011XX W Madison St,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,UNKNOWN,False,False,...,12.0,34.0,28.0,11,1168675.0,1900186.0,01/19/2024 03:40:50 PM,41.881637,-87.656088,"(41.881636544, -87.656088495)"
939,13209655,JG422078,2023-05-30 09:30:00,003XX W WASHINGTON ST,1242,DECEPTIVE PRACTICE,COMPUTER FRAUD,UNKNOWN,False,False,...,1.0,42.0,32.0,11,1174189.0,1900801.0,09/16/2023 03:41:56 PM,41.883203,-87.635823,"(41.883202953, -87.635823077)"
1192,13203348,JG415071,2023-09-07 14:35:00,052XX S NATCHEZ AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,UNKNOWN,False,False,...,8.0,23.0,56.0,11,1133934.0,1869033.0,09/15/2023 03:42:23 PM,41.796829,-87.784389,"(41.79682922, -87.784389067)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8421536,13997816,JJ451215,2021-06-14 04:18:00,021XX S INDIANA AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,UNKNOWN,False,False,...,1.0,3.0,33.0,11,NaN,NaN,10/15/2025 03:55:37 PM,NaN,NaN,NaN
8421734,13996789,JJ450326,2025-04-21 16:20:00,061XX S Sacramento Ave,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,UNKNOWN,False,False,...,8.0,15.0,66.0,11,1157438.0,1863692.0,10/15/2025 03:51:58 PM,41.781729,-87.698341,"(41.781728556, -87.698340988)"
8421787,13996755,JJ450389,2025-09-17 17:20:00,054XX W HADDON AVE,1154,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT $300 AND UNDER,UNKNOWN,False,False,...,15.0,37.0,25.0,11,1139676.0,1907128.0,10/15/2025 03:51:58 PM,41.901265,-87.762403,"(41.901264852, -87.76240333)"
8421814,13997808,JJ450790,2025-10-06 11:30:00,008XX W MONROE ST,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,UNKNOWN,False,False,...,12.0,34.0,28.0,11,NaN,NaN,10/15/2025 03:55:37 PM,NaN,NaN,NaN
8421891,13996762,JJ450018,2025-04-10 00:00:00,026XX N PULASKI RD,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,UNKNOWN,False,False,...,25.0,31.0,22.0,11,1149270.0,1917283.0,10/15/2025 03:51:58 PM,41.928951,-87.726900,"(41.928950523, -87.726899566)"

In [34]:
df[df["District"].isna()]["Beat"]

1841396    1834
1849023     124
2313231    1834
2632463     124
3438369    1112
3451704    1113
3451951    1433
3452008     234
3453184    1814
3455924    2531
3458400    2535
3461581     621
3461709     311
3463871    1112
3465041     313
3468915     823
3472409     312
3473035     922
3473836    1931
3474759    1912
3477275    1333
3485286    1424
3494617     831
3498516    2514
3502477    1013
3506680    1013
3510201     513
3511042    1834
3511748    2511
3518338    1423
3519351    1323
3531821     411
3534688    1722
3541144     731
3541939    1624
3545921    1924
3550486    1834
3554810     723
3559574     712
3563968     734
3574741    2532
3575232    2232
3576009    2412
3577350    2232
3578956    1132
3582535    2523
6355916    1654
Name: Beat, dtype: int64

In [35]:
type(df["Beat"])

pandas.Series

In [36]:
df.dtypes

ID                               int64
Case Number                        str
Date                    datetime64[us]
Block                              str
IUCR                            object
Primary Type                       str
Description                        str
Location Description               str
Arrest                            bool
Domestic                          bool
Beat                             int64
District                       float64
Ward                           float64
Community Area                 float64
FBI Code                           str
X Coordinate                   float64
Y Coordinate                   float64
Updated On                         str
Latitude                       float64
Longitude                      float64
Location                           str
dtype: object

In [40]:
df["District"]

0          10.0
1          11.0
2          14.0
3           1.0
4           1.0
           ...
8422091    12.0
8422092     6.0
8422093    17.0
8422094    22.0
8422095     4.0
Name: District, Length: 8422096, dtype: float64

- How I filled NaN district values

In [6]:
na_rows = df["District"].isna() # ilçelerin boş olduğu yerler
df.loc[na_rows, "District"] = df.loc[na_rows, "Beat"] // 100    # Beat'in ilk 2 hanesi District belirtir.

In [45]:
df.isna().sum()

ID                           0
Case Number                  0
Date                         0
Block                        0
IUCR                         0
Primary Type                 0
Description                  0
Location Description         0
Arrest                       0
Domestic                     0
Beat                         0
District                     0
Ward                    614822
Community Area          613687
FBI Code                     0
X Coordinate             93844
Y Coordinate             93844
Updated On                   0
Latitude                 93844
Longitude                93844
Location                 93844
dtype: int64

In [51]:
df.dtypes

ID                               int64
Case Number                        str
Date                    datetime64[us]
Block                              str
IUCR                            object
Primary Type                       str
Description                        str
Location Description               str
Arrest                            bool
Domestic                          bool
Beat                             int64
District                       float64
Ward                           float64
Community Area                 float64
FBI Code                           str
X Coordinate                   float64
Y Coordinate                   float64
Updated On                         str
Latitude                       float64
Longitude                      float64
Location                           str
dtype: object

In [52]:
df["Ward"].min()

np.float64(1.0)

In [53]:
df["Ward"].max()

np.float64(50.0)

In [7]:
df["Ward"] = df["Ward"].fillna(-1)   #! NaN olan Ward yerlerini -1 yaptım

In [54]:
df["Community Area"].min()

np.float64(0.0)

In [55]:
df["Community Area"].max()

np.float64(77.0)

In [8]:
df["Community Area"] = df["Community Area"].fillna(-1)   #! NaN olan Community Area yerlerini -1 yaptım

In [56]:
df[df["X Coordinate"].isna()]

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Updated On,Latitude,Longitude,Location
0,13311263,JG503434,2022-07-29 03:39:00,023XX S TROY ST,1582,OFFENSE INVOLVING CHILDREN,CHILD PORNOGRAPHY,RESIDENCE,True,False,...,10.0,25.0,30.0,17,NaN,NaN,04/18/2024 03:40:59 PM,NaN,NaN,NaN
1,13053066,JG103252,2023-01-03 16:44:00,039XX W WASHINGTON BLVD,2017,NARCOTICS,MANUFACTURE / DELIVER - CRACK,SIDEWALK,True,False,...,11.0,28.0,26.0,18,NaN,NaN,01/20/2024 03:41:12 PM,NaN,NaN,NaN
3,11227634,JB147599,2017-08-26 10:00:00,001XX W RANDOLPH ST,0281,CRIM SEXUAL ASSAULT,NON-AGGRAVATED,HOTEL/MOTEL,False,False,...,1.0,42.0,32.0,02,NaN,NaN,02/11/2018 03:57:41 PM,NaN,NaN,NaN
24,12416972,JE293535,2020-10-01 00:01:00,031XX W 53RD PL,1753,OFFENSE INVOLVING CHILDREN,SEXUAL ASSAULT OF CHILD BY FAMILY MEMBER,RESIDENCE,False,True,...,9.0,14.0,63.0,02,NaN,NaN,09/14/2023 03:41:59 PM,NaN,NaN,NaN
25,12536164,JE439378,2015-09-24 00:00:00,031XX W 53RD PL,1753,OFFENSE INVOLVING CHILDREN,SEXUAL ASSAULT OF CHILD BY FAMILY MEMBER,APARTMENT,False,True,...,9.0,14.0,63.0,02,NaN,NaN,09/14/2023 03:41:59 PM,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8422054,13998172,JJ449933,2025-05-05 08:09:00,010XX E 47TH ST,1582,OFFENSE INVOLVING CHILDREN,CHILD PORNOGRAPHY,RESIDENCE,False,False,...,2.0,4.0,39.0,17,NaN,NaN,10/15/2025 03:55:37 PM,NaN,NaN,NaN
8422070,13997611,JJ451393,2025-06-07 19:45:00,058XX W SUPERIOR ST,1135,DECEPTIVE PRACTICE,INSURANCE FRAUD,HOSPITAL BUILDING / GROUNDS,False,False,...,15.0,29.0,25.0,11,NaN,NaN,10/15/2025 03:55:37 PM,NaN,NaN,NaN
8422085,13997185,JJ450995,2025-10-06 10:30:00,078XX S LAFLIN ST,0610,BURGLARY,FORCIBLE ENTRY,RESIDENCE,False,False,...,6.0,17.0,71.0,05,NaN,NaN,10/15/2025 03:55:37 PM,NaN,NaN,NaN
8422086,13998133,JJ450942,2025-10-05 12:01:00,001XX E RANDOLPH ST,1210,DECEPTIVE PRACTICE,THEFT OF LABOR / SERVICES,RESTAURANT,False,False,...,1.0,42.0,32.0,11,NaN,NaN,10/15/2025 03:55:37 PM,NaN,NaN,NaN
8422089,13997516,JJ451537,2025-09-24 12:00:00,039XX W WASHINGTON BLVD,1365,CRIMINAL TRESPASS,TO RESIDENCE,APARTMENT,False,False,...,11.0,28.0,26.0,26,NaN,NaN,10/15/2025 03:55:37 PM,NaN,NaN,NaN

In [57]:
df["X Coordinate"].min()

np.float64(0.0)

In [9]:
df["X Coordinate"] = df["X Coordinate"].fillna(-1)   #! NaN olan X Coordinate yerlerini -1 yaptım

In [58]:
df["Y Coordinate"].min()

np.float64(0.0)

In [60]:
df["Longitude"].min()

np.float64(-91.686565684)

In [61]:
df["Latitude"].min()

np.float64(36.619446395)

In [62]:
df[df["Longitude"] == -1]

Empty DataFrame
Columns: [ID, Case Number, Date, Block, IUCR, Primary Type, Description, Location Description, Arrest, Domestic, Beat, District, Ward, Community Area, FBI Code, X Coordinate, Y Coordinate, Updated On, Latitude, Longitude, Location]
Index: []

[0 rows x 21 columns]

In [63]:
df[df["Latitude"] == -1]

Empty DataFrame
Columns: [ID, Case Number, Date, Block, IUCR, Primary Type, Description, Location Description, Arrest, Domestic, Beat, District, Ward, Community Area, FBI Code, X Coordinate, Y Coordinate, Updated On, Latitude, Longitude, Location]
Index: []

[0 rows x 21 columns]

In [10]:
df["Y Coordinate"] = df["Y Coordinate"].fillna(-1)   #! NaN olan Y Coordinate yerlerini -1 yaptım
df["Longitude"] = df["Longitude"].fillna(-1)   #! NaN olan Longitude yerlerini -1 yaptım
df["Latitude"] = df["Latitude"].fillna(-1)   #! NaN olan Latitude yerlerini -1 yaptım

In [11]:
df["Location"] = df["Location"].fillna("UNKNOWN")   #! NaN olan Location "UNKNOWN" yaptım

In [72]:
df.isna().sum()

ID                      0
Case Number             0
Date                    0
Block                   0
IUCR                    0
Primary Type            0
Description             0
Location Description    0
Arrest                  0
Domestic                0
Beat                    0
District                0
Ward                    0
Community Area          0
FBI Code                0
X Coordinate            0
Y Coordinate            0
Updated On              0
Latitude                0
Longitude               0
Location                0
dtype: int64

In [76]:
df.dtypes

ID                               int64
Case Number                        str
Date                    datetime64[us]
Block                              str
IUCR                            object
Primary Type                       str
Description                        str
Location Description               str
Arrest                            bool
Domestic                          bool
Beat                             int64
District                       float64
Ward                           float64
Community Area                 float64
FBI Code                           str
X Coordinate                   float64
Y Coordinate                   float64
Updated On                         str
Latitude                       float64
Longitude                      float64
Location                           str
dtype: object

In [73]:
df

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Updated On,Latitude,Longitude,Location
0,13311263,JG503434,2022-07-29 03:39:00,023XX S TROY ST,1582,OFFENSE INVOLVING CHILDREN,CHILD PORNOGRAPHY,RESIDENCE,True,False,...,10.0,25.0,30.0,17,-1.0,-1.0,04/18/2024 03:40:59 PM,-1.000000,-1.000000,UNKNOWN
1,13053066,JG103252,2023-01-03 16:44:00,039XX W WASHINGTON BLVD,2017,NARCOTICS,MANUFACTURE / DELIVER - CRACK,SIDEWALK,True,False,...,11.0,28.0,26.0,18,-1.0,-1.0,01/20/2024 03:41:12 PM,-1.000000,-1.000000,UNKNOWN
2,12131221,JD327000,2020-08-10 09:45:00,015XX N DAMEN AVE,0326,ROBBERY,AGGRAVATED VEHICULAR HIJACKING,STREET,True,False,...,14.0,1.0,24.0,03,1162795.0,1909900.0,05/17/2025 03:40:52 PM,41.908418,-87.677407,"(41.908417822, -87.67740693)"
3,11227634,JB147599,2017-08-26 10:00:00,001XX W RANDOLPH ST,0281,CRIM SEXUAL ASSAULT,NON-AGGRAVATED,HOTEL/MOTEL,False,False,...,1.0,42.0,32.0,02,-1.0,-1.0,02/11/2018 03:57:41 PM,-1.000000,-1.000000,UNKNOWN
4,13203321,JG415333,2023-09-06 17:00:00,002XX N Wells st,1320,CRIMINAL DAMAGE,TO VEHICLE,PARKING LOT / GARAGE (NON RESIDENTIAL),False,False,...,1.0,42.0,32.0,14,1174694.0,1901831.0,11/04/2023 03:40:18 PM,41.886018,-87.633938,"(41.886018055, -87.633937881)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8422091,13991734,JJ444423,2025-10-07 21:00:00,010XX N MILWAUKEE AVE,0910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,...,12.0,27.0,24.0,07,1166630.0,1907361.0,10/15/2025 03:55:37 PM,41.901369,-87.663392,"(41.901369302, -87.663391932)"
8422092,13991229,JJ443785,2025-10-07 22:26:00,079XX S HALSTED ST,0454,BATTERY,"AGGRAVATED P.O. - HANDS, FISTS, FEET, NO / MIN...",PARKING LOT / GARAGE (NON RESIDENTIAL),True,False,...,6.0,17.0,71.0,08B,1172344.0,1852279.0,10/15/2025 03:55:37 PM,41.750095,-87.644027,"(41.750094836, -87.644027249)"
8422093,13996340,JJ449975,2025-09-29 17:20:00,027XX W MONTROSE AVE,0760,BURGLARY,BURGLARY FROM MOTOR VEHICLE,STREET,False,False,...,17.0,33.0,16.0,06,1157140.0,1929112.0,10/15/2025 03:51:58 PM,41.961254,-87.697657,"(41.961253689, -87.697657333)"
8422094,13990920,JJ443318,2025-10-07 14:56:00,089XX S WALLACE ST,0486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,False,True,...,22.0,21.0,71.0,08B,1173869.0,1845664.0,10/15/2025 03:55:37 PM,41.731909,-87.638635,"(41.731908752, -87.638634675)"
8422095,13990549,JJ442752,2025-10-07 03:30:00,131XX S CARONDOLET AVE,1320,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,False,...,4.0,10.0,55.0,14,1198434.0,1818345.0,10/15/2025 03:55:37 PM,41.656363,-87.549555,"(41.65636344, -87.549555301)"

In [ ]:
df[df.duplicated()] #* Duplicate veri yok :)

Empty DataFrame
Columns: [ID, Case Number, Date, Block, IUCR, Primary Type, Description, Location Description, Arrest, Domestic, Beat, District, Ward, Community Area, FBI Code, X Coordinate, Y Coordinate, Updated On, Latitude, Longitude, Location]
Index: []

[0 rows x 21 columns]

In [12]:
df["Updated On"] = pd.to_datetime(df["Updated On"], unit="us")

In [79]:
df.dtypes

ID                               int64
Case Number                        str
Date                    datetime64[us]
Block                              str
IUCR                            object
Primary Type                       str
Description                        str
Location Description               str
Arrest                            bool
Domestic                          bool
Beat                             int64
District                       float64
Ward                           float64
Community Area                 float64
FBI Code                           str
X Coordinate                   float64
Y Coordinate                   float64
Updated On              datetime64[us]
Latitude                       float64
Longitude                      float64
Location                           str
dtype: object

In [13]:
df

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Updated On,Latitude,Longitude,Location
0,13311263,JG503434,2022-07-29 03:39:00,023XX S TROY ST,1582,OFFENSE INVOLVING CHILDREN,CHILD PORNOGRAPHY,RESIDENCE,True,False,...,10.0,25.0,30.0,17,-1.0,-1.0,2024-04-18 15:40:59,-1.000000,-1.000000,UNKNOWN
1,13053066,JG103252,2023-01-03 16:44:00,039XX W WASHINGTON BLVD,2017,NARCOTICS,MANUFACTURE / DELIVER - CRACK,SIDEWALK,True,False,...,11.0,28.0,26.0,18,-1.0,-1.0,2024-01-20 15:41:12,-1.000000,-1.000000,UNKNOWN
2,12131221,JD327000,2020-08-10 09:45:00,015XX N DAMEN AVE,0326,ROBBERY,AGGRAVATED VEHICULAR HIJACKING,STREET,True,False,...,14.0,1.0,24.0,03,1162795.0,1909900.0,2025-05-17 15:40:52,41.908418,-87.677407,"(41.908417822, -87.67740693)"
3,11227634,JB147599,2017-08-26 10:00:00,001XX W RANDOLPH ST,0281,CRIM SEXUAL ASSAULT,NON-AGGRAVATED,HOTEL/MOTEL,False,False,...,1.0,42.0,32.0,02,-1.0,-1.0,2018-02-11 15:57:41,-1.000000,-1.000000,UNKNOWN
4,13203321,JG415333,2023-09-06 17:00:00,002XX N Wells st,1320,CRIMINAL DAMAGE,TO VEHICLE,PARKING LOT / GARAGE (NON RESIDENTIAL),False,False,...,1.0,42.0,32.0,14,1174694.0,1901831.0,2023-11-04 15:40:18,41.886018,-87.633938,"(41.886018055, -87.633937881)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8422091,13991734,JJ444423,2025-10-07 21:00:00,010XX N MILWAUKEE AVE,0910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,...,12.0,27.0,24.0,07,1166630.0,1907361.0,2025-10-15 15:55:37,41.901369,-87.663392,"(41.901369302, -87.663391932)"
8422092,13991229,JJ443785,2025-10-07 22:26:00,079XX S HALSTED ST,0454,BATTERY,"AGGRAVATED P.O. - HANDS, FISTS, FEET, NO / MIN...",PARKING LOT / GARAGE (NON RESIDENTIAL),True,False,...,6.0,17.0,71.0,08B,1172344.0,1852279.0,2025-10-15 15:55:37,41.750095,-87.644027,"(41.750094836, -87.644027249)"
8422093,13996340,JJ449975,2025-09-29 17:20:00,027XX W MONTROSE AVE,0760,BURGLARY,BURGLARY FROM MOTOR VEHICLE,STREET,False,False,...,17.0,33.0,16.0,06,1157140.0,1929112.0,2025-10-15 15:51:58,41.961254,-87.697657,"(41.961253689, -87.697657333)"
8422094,13990920,JJ443318,2025-10-07 14:56:00,089XX S WALLACE ST,0486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,False,True,...,22.0,21.0,71.0,08B,1173869.0,1845664.0,2025-10-15 15:55:37,41.731909,-87.638635,"(41.731908752, -87.638634675)"
8422095,13990549,JJ442752,2025-10-07 03:30:00,131XX S CARONDOLET AVE,1320,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,False,...,4.0,10.0,55.0,14,1198434.0,1818345.0,2025-10-15 15:55:37,41.656363,-87.549555,"(41.65636344, -87.549555301)"

In [15]:
df["IUCR"] = df["IUCR"].astype(str)

In [16]:
df.dtypes

ID                               int64
Case Number                        str
Date                    datetime64[us]
Block                              str
IUCR                               str
Primary Type                       str
Description                        str
Location Description               str
Arrest                            bool
Domestic                          bool
Beat                             int64
District                       float64
Ward                           float64
Community Area                 float64
FBI Code                           str
X Coordinate                   float64
Y Coordinate                   float64
Updated On              datetime64[us]
Latitude                       float64
Longitude                      float64
Location                           str
dtype: object

In [17]:
df.to_parquet("analyzed_crime_data.parquet", index=False)